version: "2"

volumes:
    html: ${PWD}/web


services:
    nginx:
        build: dockers/nginx
        volumes:
            - html:/usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm
            - mariadb
            - redis
        restart: always

    php-fpm:
        build: dockers/php-fpm
        volumes:
            - html:/usr/share/nginx/html
        ports:
            - "2222:22"
        restart: always

    mariadb:
        build: dockers/mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
            - MYSQL_DATABASE=XE_DB
            - MYSQL_USER=XE_USER
            - MYSQL_PASSWORD=USER_PASSWORD
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always

    redis:
        image: redis
        restart: always

    ssh:
        build: dockers/ssh
        ports:
            - "22:22"
        volumes:
            - html:/usr/share/nginx/html
